[package]
name = "cargo-touch"
version = "0.2.0"
authors = ["David McGillicuddy <david.mcgillicuddy@moixa.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cargo_toml = "0.11.5"
env_logger = "0.9.0"
filetime = "0.2.17"
log = "0.4.17"
